=== Project-MONAI/model-zoo/models/lung_nodule_ct_detection/eval/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "schema": {
            "description": "URL of the schema file.",
            "type": "string"
        },
        "version": {
            "description": "version number of the model package.",
            "type": "string"
        },
        "changelog": {
            "description": "dictionary relating previous version names to strings describing the version.",
            "type": "object"
        },
        "monai_version": {
            "description": "version of MONAI the model package was generated on.",
            "type": "string"
        },
        "pytorch_version": {
            "description": "version of PyTorch the model package was generated on.",
            "type": "string"
        },
        "numpy_version": {
            "description": "version of NumPy the model package was generated on.",
            "type": "string"
        },
        "optional_packages_version": {
            "description": "dictionary relating optional package names to their versions.",
            "type": "object"
        },
        "task": {
            "description": "plain-language description of what the model is meant to do.",
            "type": "string"
        },
        "description": {
            "description": "longer form plain-language description of what the model is, what it does, etc.",
            "type": "string"
        },
        "authors": {
            "description": "state author(s) of the model package.",
            "type": "string"
        },
        "copyright": {
            "description": "state copyright of the model package.",
            "type": "string"
        },
        "data_source": {
            "description": "where to download or prepare the data used in this model package.",
            "type": "string"
        },
        "data_type": {
            "description": "type of the data, like: `dicom`, `nibabel`, etc.",
            "type": "string"
        },
        "image_classes": {
            "description": "description for every class of the input image.",
            "type": "string"
        },
        "label_classes": {
            "description": "description for every class of the input label.",
            "type": "string"
        },
        "pred_classes": {
            "description": "description for every class of the output prediction.",
            "type": "string"
        },
        "eval_metrics": {
            "description": "dictionary relating evaluation metrics to the achieved scores.",
            "type": "object"
        },
        "intended_use": {
            "description": "what the model package is to be used for, ie. what task it accomplishes.",
            "type": "string"
        },
        "references": {
            "description": "list of published referenced relating to the model package.",
            "type": "array"
        },
        "network_data_format": {
            "description": "defines the format, shape, and meaning of inputs and outputs to the model.",
            "type": "object",
            "properties": {
                "inputs": {
                    "type": "object",
                    "properties": {
                        "image": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string"
                                },
                                "format": {
                                    "type": "string"
                                },
                                "num_channels": {
                                    "type": "integer"
                                },
                                "spatial_shape": {
                                    "type": "array"
                                },
                                "dtype": {
                                    "type": "string"
                                },
                                "value_range": {
                                    "type": "array",
                                    "items": {
                                        "type": "number"
                                    }
                                },
                                "is_patch_data": {
                                    "type": "boolean"
                                },
                                "channel_def": {
                                    "type": "object"
                                }
                            },
                            "required": [
                                "type",
                                "format",
                                "num_channels",
                                "spatial_shape",
                                "dtype",
                                "value_range"
                            ]
                        },
                        "label": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string"
                                },
                                "format": {
                                    "type": "string"
                                },
                                "num_channels": {
                                    "type": "integer"
                                },
                                "spatial_shape": {
                                    "type": "array"
                                },
                                "dtype": {
                                    "type": "string"
                                },
                                "value_range": {
                                    "type": "array",
                                    "items": {
                                        "type": "number"
                                    }
                                },
                                "is_patch_data": {
                                    "type": "boolean"
                                },
                                "channel_def": {
                                    "type": "object"
                                }
                            },
                            "required": [
                                "type",
                                "format",
                                "num_channels",
                                "spatial_shape",
                                "dtype",
                                "value_range"
                            ]
                        }
                    },
                    "required": [
                        "image"
                    ]
                },
                "outputs": {
                    "type": "object",
                    "properties": {
                        "pred": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string"
                                },
                                "format": {
                                    "type": "string"
                                },
                                "num_channels": {
                                    "type": "integer"
                                },
                                "spatial_shape": {
                                    "type": "array"
                                },
                                "dtype": {
                                    "type": "string"
                                },
                                "value_range": {
                                    "type": "array",
                                    "items": {
                                        "type": "number"
                                    }
                                },
                                "is_patch_data": {
                                    "type": "boolean"
                                },
                                "channel_def": {
                                    "type": "object"
                                }
                            },
                            "required": [
                                "type",
                                "format",
                                "num_channels",
                                "spatial_shape",
                                "dtype",
                                "value_range"
                            ]
                        }
                    },
                    "required": [
                        "pred"
                    ]
                }
            },
            "required": [
                "inputs",
                "outputs"
            ]
        }
    },
    "required": [
        "schema",
        "version",
        "monai_version",
        "pytorch_version",
        "numpy_version",
        "optional_packages_version",
        "task",
        "description",
        "authors",
        "copyright",
        "network_data_format"
    ]
}

=== Project-MONAI/model-zoo/models/renalStructures_UNEST_segmentation/configs/metadata.json
{
    "schema": "https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json",
    "version": "0.2.0",
    "changelog": {
        "0.2.0": "update license files",
        "0.1.2": "fixed the dimension in convolution according to MONAI 1.0 update",
        "0.1.1": "fixed the model state dict name",
        "0.1.0": "complete the model package"
    },
    "monai_version": "0.9.0",
    "pytorch_version": "1.10.0",
    "numpy_version": "1.21.2",
    "optional_packages_version": {
        "nibabel": "3.2.1",
        "pytorch-ignite": "0.4.8",
        "einops": "0.4.1",
        "fire": "0.4.0",
        "timm": "0.6.7"
    },
    "task": "Renal segmentation",
    "description": "A transformer-based model for renal segmentation from CT image",
    "authors": "Vanderbilt University + MONAI team",
    "copyright": "Copyright (c) MONAI Consortium",
    "data_source": "RawData.zip",
    "data_type": "nibabel",
    "image_classes": "single channel data, intensity scaled to [0, 1]",
    "label_classes": "1: Kideny Cortex, 2:Medulla, 3:Pelvicalyceal system",
    "pred_classes": "1: Kideny Cortex, 2:Medulla, 3:Pelvicalyceal system",
    "eval_metrics": {
        "mean_dice": 0.85
    },
    "intended_use": "This is an example, not to be used for diagnostic purposes",
    "references": [
        "Tang, Yucheng, et al. 'Self-supervised pre-training of swin transformers for 3d medical image analysis. arXiv preprint arXiv:2111.14791 (2021). https://arxiv.org/abs/2111.14791."
    ],
    "network_data_format": {
        "inputs": {
            "image": {
                "type": "image",
                "format": "hounsfield",
                "modality": "CT",
                "num_channels": 1,
                "spatial_shape": [
                    96,
                    96,
                    96
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    1
                ],
                "is_patch_data": true,
                "channel_def": {
                    "0": "image"
                }
            }
        },
        "outputs": {
            "pred": {
                "type": "image",
                "format": "segmentation",
                "num_channels": 4,
                "spatial_shape": [
                    96,
                    96,
                    96
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    1
                ],
                "is_patch_data": true,
                "channel_def": {
                    "0": "background",
                    "1": "kidney cortex",
                    "2": "medulla",
                    "3": "pelvicalyceal system"
                }
            }
        }
    }
}

=== Project-MONAI/model-zoo/models/lung_nodule_ct_detection/configs/metadata.json
{
    "schema": "https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json",
    "version": "0.1.1",
    "changelog": {
        "0.1.0": "complete the model package",
        "0.1.1": "add reference for LIDC dataset"
    },
    "monai_version": "0.9.1",
    "pytorch_version": "1.12.0",
    "numpy_version": "1.22.4",
    "optional_packages_version": {
        "nibabel": "4.0.1",
        "pytorch-ignite": "0.4.9"
    },
    "task": "CT lung nodule detection",
    "description": "A pre-trained model for volumetric (3D) detection of the lung lesion from CT image on LUNA16 dataset",
    "authors": "MONAI team",
    "copyright": "Copyright (c) MONAI Consortium",
    "data_source": "https://luna16.grand-challenge.org/Home/",
    "data_type": "nibabel",
    "image_classes": "1 channel data, CT at 0.703125 x 0.703125 x 1.25 mm",
    "label_classes": "dict data, containing Nx6 box and Nx1 classification labels.",
    "pred_classes": "dict data, containing Nx6 box, Nx1 classification labels, Nx1 classification scores.",
    "eval_metrics": {
        "val_coco": 0,
        "froc": 0
    },
    "intended_use": "This is an example, not to be used for diagnostic purposes",
    "references": [
        "Lin, Tsung-Yi, et al. 'Focal loss for dense object detection. ICCV 2017"
    ],
    "network_data_format": {
        "inputs": {
            "image": {
                "type": "image",
                "format": "magnitude",
                "modality": "CT",
                "num_channels": 1,
                "spatial_shape": [
                    "16*n",
                    "16*n",
                    "8*n"
                ],
                "dtype": "float16",
                "value_range": [
                    0,
                    1
                ],
                "is_patch_data": true,
                "channel_def": {
                    "0": "image"
                }
            }
        },
        "outputs": {
            "pred": {
                "type": "object",
                "format": "dict",
                "dtype": "float16",
                "num_channels": 1,
                "spatial_shape": [
                    "n",
                    "n",
                    "n"
                ],
                "value_range": [
                    -10000,
                    10000
                ]
            }
        }
    }
}

=== Project-MONAI/model-zoo/models/brats_mri_segmentation/configs/metadata.json
{
    "schema": "https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json",
    "version": "0.1.1",
    "changelog": {
        "0.1.1": "update for MetaTensor",
        "0.1.0": "complete the model package"
    },
    "monai_version": "0.9.1",
    "pytorch_version": "1.13.0",
    "numpy_version": "1.22.4",
    "optional_packages_version": {
        "nibabel": "4.0.1",
        "pytorch-ignite": "0.4.9"
    },
    "task": "Multimodal Brain Tumor segmentation",
    "description": "A pre-trained model for volumetric (3D) segmentation of brain tumor subregions from multimodal MRIs based on BraTS 2018 data",
    "authors": "MONAI team",
    "copyright": "Copyright (c) MONAI Consortium",
    "data_source": "https://www.med.upenn.edu/sbia/brats2018/data.html",
    "data_type": "nibabel",
    "image_classes": "4 channel data, T1c, T1, T2, FLAIR at 1x1x1 mm",
    "label_classes": "3 channel data, channel 0 for Tumor core, channel 1 for Whole tumor, channel 2 for Enhancing tumor",
    "pred_classes": "3 channels data, same as label_classes",
    "eval_metrics": {
        "val_mean_dice": 0.8518,
        "val_mean_dice_tc": 0.8559,
        "val_mean_dice_wt": 0.9026,
        "val_mean_dice_et": 0.7905
    },
    "intended_use": "This is an example, not to be used for diagnostic purposes",
    "references": [
        "Myronenko, Andriy. '3D MRI brain tumor segmentation using autoencoder regularization.' International MICCAI Brainlesion Workshop. Springer, Cham, 2018. https://arxiv.org/abs/1810.11654"
    ],
    "network_data_format": {
        "inputs": {
            "image": {
                "type": "image",
                "format": "magnitude",
                "modality": "MR",
                "num_channels": 4,
                "spatial_shape": [
                    "8*n",
                    "8*n",
                    "8*n"
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    1
                ],
                "is_patch_data": true,
                "channel_def": {
                    "0": "image"
                }
            }
        },
        "outputs": {
            "pred": {
                "type": "image",
                "format": "segmentation",
                "num_channels": 3,
                "spatial_shape": [
                    "8*n",
                    "8*n",
                    "8*n"
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    1
                ],
                "is_patch_data": true,
                "channel_def": {
                    "0": "background",
                    "1": "spleen"
                }
            }
        }
    }
}

=== Project-MONAI/model-zoo/models/pathology_multiple_instance_learning_classification/configs/metadata.json
{
    "schema": "https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json",
    "version": "0.1.0",
    "changelog": {
        "0.1.0": "complete the model package"
    },
    "monai_version": "1.1.0",
    "pytorch_version": "1.13.0",
    "numpy_version": "1.22.2",
    "optional_packages_version": {
        "cucim": "22.10.0",
        "gdown": "4.5.4"
    },
    "task": " Multiple Instance Learning (MIL) classification from Whole Slide Images (WSI).",
    "description": "A pre-trained baseline model for Multiple Instance Learning (MIL) classification from Whole Slide Images (WSI) based on PANDA 2020 data",
    "authors": "MONAI team",
    "copyright": "Copyright (c) MONAI Consortium",
    "data_source": "https://www.kaggle.com/c/prostate-cancer-grade-assessment/",
    "data_type": "tiff",
    "image_classes": "3 channel RGB data, 2D TIFF WSI",
    "label_classes": "5 classes, ISUP grade",
    "pred_classes": "5 classes, ISUP grade",
    "eval_metrics": {
        "QWK": 0.9071
    },
    "intended_use": "This is an example, not to be used for diagnostic purposes",
    "references": [
        "Andriy Myronenko, Ziyue Xu, Dong Yang, Holger Roth, Daguang Xu: 'Accounting for Dependencies in Deep Learning Based Multiple Instance Learning for Whole Slide Imaging'. In MICCAI (2021). https://arxiv.org/abs/2111.01556"
    ],
    "network_data_format": {
        "inputs": {
            "image": {
                "type": "image",
                "format": "magnitude",
                "modality": "TIFF",
                "num_channels": 3,
                "spatial_shape": [
                    "256*n",
                    "256*n"
                ],
                "dtype": "uint8",
                "value_range": [],
                "is_patch_data": true,
                "channel_def": {
                    "0": "R",
                    "1": "G",
                    "2": "B"
                }
            }
        },
        "outputs": {
            "pred": {
                "type": "image",
                "format": "labels",
                "dtype": "int",
                "value_range": [
                    0,
                    5
                ],
                "num_channels": 1,
                "spatial_shape": [
                    1
                ],
                "is_patch_data": false,
                "channel_def": {
                    "0": "ISUP grade"
                }
            }
        }
    }
}
