=== Project-MONAI/model-zoo/models/lung_nodule_ct_detection/eval/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "schema": {
            "description": "URL of the schema file.",
            "type": "string"
        },
        "version": {
            "description": "version number of the model package.",
            "type": "string"
        },
        "changelog": {
            "description": "dictionary relating previous version names to strings describing the version.",
            "type": "object"
        },
        "monai_version": {
            "description": "version of MONAI the model package was generated on.",
            "type": "string"
        },
        "pytorch_version": {
            "description": "version of PyTorch the model package was generated on.",
            "type": "string"
        },
        "numpy_version": {
            "description": "version of NumPy the model package was generated on.",
            "type": "string"
        },
        "optional_packages_version": {
            "description": "dictionary relating optional package names to their versions.",
            "type": "object"
        },
        "task": {
            "description": "plain-language description of what the model is meant to do.",
            "type": "string"
        },
        "description": {
            "description": "longer form plain-language description of what the model is, what it does, etc.",
            "type": "string"
        },
        "authors": {
            "description": "state author(s) of the model package.",
            "type": "string"
        },
        "copyright": {
            "description": "state copyright of the model package.",
            "type": "string"
        },
        "data_source": {
            "description": "where to download or prepare the data used in this model package.",
            "type": "string"
        },
        "data_type": {
            "description": "type of the data, like: `dicom`, `nibabel`, etc.",
            "type": "string"
        },
        "image_classes": {
            "description": "description for every class of the input image.",
            "type": "string"
        },
        "label_classes": {
            "description": "description for every class of the input label.",
            "type": "string"
        },
        "pred_classes": {
            "description": "description for every class of the output prediction.",
            "type": "string"
        },
        "eval_metrics": {
            "description": "dictionary relating evaluation metrics to the achieved scores.",
            "type": "object"
        },
        "intended_use": {
            "description": "what the model package is to be used for, ie. what task it accomplishes.",
            "type": "string"
        },
        "references": {
            "description": "list of published referenced relating to the model package.",
            "type": "array"
        },
        "network_data_format": {
            "description": "defines the format, shape, and meaning of inputs and outputs to the model.",
            "type": "object",
            "properties": {
                "inputs": {
                    "type": "object",
                    "properties": {
                        "image": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string"
                                },
                                "format": {
                                    "type": "string"
                                },
                                "num_channels": {
                                    "type": "integer"
                                },
                                "spatial_shape": {
                                    "type": "array"
                                },
                                "dtype": {
                                    "type": "string"
                                },
                                "value_range": {
                                    "type": "array",
                                    "items": {
                                        "type": "number"
                                    }
                                },
                                "is_patch_data": {
                                    "type": "boolean"
                                },
                                "channel_def": {
                                    "type": "object"
                                }
                            },
                            "required": [
                                "type",
                                "format",
                                "num_channels",
                                "spatial_shape",
                                "dtype",
                                "value_range"
                            ]
                        },
                        "label": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string"
                                },
                                "format": {
                                    "type": "string"
                                },
                                "num_channels": {
                                    "type": "integer"
                                },
                                "spatial_shape": {
                                    "type": "array"
                                },
                                "dtype": {
                                    "type": "string"
                                },
                                "value_range": {
                                    "type": "array",
                                    "items": {
                                        "type": "number"
                                    }
                                },
                                "is_patch_data": {
                                    "type": "boolean"
                                },
                                "channel_def": {
                                    "type": "object"
                                }
                            },
                            "required": [
                                "type",
                                "format",
                                "num_channels",
                                "spatial_shape",
                                "dtype",
                                "value_range"
                            ]
                        }
                    },
                    "required": [
                        "image"
                    ]
                },
                "outputs": {
                    "type": "object",
                    "properties": {
                        "pred": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string"
                                },
                                "format": {
                                    "type": "string"
                                },
                                "num_channels": {
                                    "type": "integer"
                                },
                                "spatial_shape": {
                                    "type": "array"
                                },
                                "dtype": {
                                    "type": "string"
                                },
                                "value_range": {
                                    "type": "array",
                                    "items": {
                                        "type": "number"
                                    }
                                },
                                "is_patch_data": {
                                    "type": "boolean"
                                },
                                "channel_def": {
                                    "type": "object"
                                }
                            },
                            "required": [
                                "type",
                                "format",
                                "num_channels",
                                "spatial_shape",
                                "dtype",
                                "value_range"
                            ]
                        }
                    },
                    "required": [
                        "pred"
                    ]
                }
            },
            "required": [
                "inputs",
                "outputs"
            ]
        }
    },
    "required": [
        "schema",
        "version",
        "monai_version",
        "pytorch_version",
        "numpy_version",
        "optional_packages_version",
        "task",
        "description",
        "authors",
        "copyright",
        "network_data_format"
    ]
}

=== Project-MONAI/model-zoo/models/multi_organ_segmentation/configs/metadata.json
{
    "schema": "https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json",
    "version": "0.0.2",
    "changelog": {
        "0.0.1": "initialize the model package structure",
        "0.0.2": "Retrain with new MONAI"
    },
    "monai_version": "1.2.0rc7",
    "pytorch_version": "2.0.0a0+1767026",
    "numpy_version": "1.22.2",
    "optional_packages_version": {
        "fire": "0.5.0",
        "nibabel": "5.1.0",
        "pytorch-ignite": "0.4.11"
    },
    "task": "Multi-organ segmentation in abdominal CT",
    "description": "DiNTS architectures for volumetric (3D) segmentation of the abdominal from CT image",
    "authors": "Chen Shen, Holger R. Roth, Kazunari Misawa, Kensaku Mori",
    "copyright": "",
    "data_source": "Aichi Cancer Center, Japan",
    "data_type": "nibabel",
    "image_classes": "single channel data, intensity scaled to [0, 1]",
    "label_classes": "eight channels data, 1 is artery, 2 is portal vein, 3 is liver, 4 is spleen, 5 is stomach, 6 is gallbladder, 7 is pancreas, 0 is everything else",
    "pred_classes": "8 channels OneHot data, 1 is artery, 2 is portal vein, 3 is liver, 4 is spleen, 5 is stomach, 6 is gallbladder, 7 is pancreas, 0 is background",
    "eval_metrics": {
        "mean_dice": 0.88
    },
    "references": [
        "He, Y., Yang, D., Roth, H., Zhao, C. and Xu, D., 2021. Dints: Differentiable neural network topology search for 3d medical image segmentation. In Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (pp. 5841-5850).",
        "Roth, H., Shen C, Oda H., Sugino T., Oda M., Hayashi Y., Misawa K., Mori K., 2018. A multi-scale pyramid of 3D fully convolutional networks for abdominal multi-organ segmentation. International conference on medical image computing and computer-assisted intervention",
        "Shen, C., Roth, H. R., Nath, V., Hayashi, Y., Oda, M., Misawa, K., Mori, K., 2022. Effective hyperparameter optimization with proxy data for multi-organ segmentation. In Medical Imaging 2022: Image Processing (Vol. 12032, pp. 200-206)"
    ],
    "network_data_format": {
        "inputs": {
            "image": {
                "type": "image",
                "format": "hounsfield",
                "modality": "CT",
                "num_channels": 1,
                "spatial_shape": [
                    96,
                    96,
                    96
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    1
                ],
                "is_patch_data": true,
                "channel_def": {
                    "0": "image"
                }
            }
        },
        "outputs": {
            "pred": {
                "type": "image",
                "format": "segmentation",
                "num_channels": 8,
                "spatial_shape": [
                    96,
                    96,
                    96
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7
                ],
                "is_patch_data": true,
                "channel_def": {
                    "0": "background",
                    "1": "artery",
                    "2": "portal vein",
                    "3": "liver",
                    "4": "spleen",
                    "5": "stomach",
                    "6": "gallbladder",
                    "7": "pancreas"
                }
            }
        }
    }
}

=== Project-MONAI/model-zoo/models/pancreas_ct_dints_segmentation/configs/metadata.json
{
    "schema": "https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json",
    "version": "0.1.0",
    "changelog": {
        "0.1.0": "complete the model package",
        "0.0.1": "initialize the model package structure"
    },
    "monai_version": "0.9.0",
    "pytorch_version": "1.10.0",
    "numpy_version": "1.21.2",
    "optional_packages_version": {
        "nibabel": "3.2.1"
    },
    "task": "Neural architecture search on pancreas CT segmentation",
    "description": "Searched architectures for volumetric (3D) segmentation of the pancreas from CT image",
    "authors": "MONAI team",
    "copyright": "Copyright (c) MONAI Consortium",
    "data_source": "Task07_Pancreas.tar from http://medicaldecathlon.com/",
    "data_type": "nibabel",
    "image_classes": "single channel data, intensity scaled to [0, 1]",
    "label_classes": "single channel data, 1 is pancreas, 2 is pancreatic tumor, 0 is everything else",
    "pred_classes": "3 channels OneHot data, channel 1 is pancreas, channel 2 is pancreatic tumor, channel 0 is background",
    "eval_metrics": {
        "mean_dice": 0.65
    },
    "intended_use": "This is an example, not to be used for diagnostic purposes",
    "references": [
        "He, Y., Yang, D., Roth, H., Zhao, C. and Xu, D., 2021. Dints: Differentiable neural network topology search for 3d medical image segmentation. In Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition (pp. 5841-5850)."
    ],
    "network_data_format": {
        "inputs": {
            "image": {
                "type": "image",
                "format": "hounsfield",
                "modality": "CT",
                "num_channels": 1,
                "spatial_shape": [
                    96,
                    96,
                    96
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    1
                ],
                "is_patch_data": true,
                "channel_def": {
                    "0": "image"
                }
            }
        },
        "outputs": {
            "pred": {
                "type": "image",
                "format": "segmentation",
                "num_channels": 3,
                "spatial_shape": [
                    96,
                    96,
                    96
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    1,
                    2
                ],
                "is_patch_data": true,
                "channel_def": {
                    "0": "background",
                    "1": "pancreas",
                    "2": "pancreatic tumor"
                }
            }
        }
    }
}

=== Project-MONAI/model-zoo/models/segmentation_template/configs/metadata.json
{
    "schema": "https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json",
    "version": "0.0.1",
    "changelog": {
        "0.0.1": "Initial version"
    },
    "monai_version": "1.3.0",
    "pytorch_version": "2.0.1",
    "numpy_version": "1.25.2",
    "optional_packages_version": {},
    "task": "Segmentation of randomly generated spheres in 3D images",
    "description": "This is a template bundle for segmenting in 3D, take this as a basis for your own bundles.",
    "authors": "Eric Kerfoot",
    "copyright": "Copyright (c) 2023 MONAI Consortium",
    "network_data_format": {
        "inputs": {
            "image": {
                "type": "image",
                "format": "magnitude",
                "modality": "MR",
                "num_channels": 1,
                "spatial_shape": [
                    128,
                    128,
                    128
                ],
                "dtype": "float32",
                "value_range": [],
                "is_patch_data": false,
                "channel_def": {
                    "0": "image"
                }
            }
        },
        "outputs": {
            "pred": {
                "type": "image",
                "format": "segmentation",
                "num_channels": 4,
                "spatial_shape": [
                    128,
                    128,
                    128
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    3
                ],
                "is_patch_data": false,
                "channel_def": {
                    "0": "background",
                    "1": "category 1",
                    "2": "category 1",
                    "3": "category 1"
                }
            }
        }
    }
}

=== Project-MONAI/model-zoo/models/wholeBrainSeg_Large_UNEST_segmentation/configs/metadata.json
{
    "schema": "https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json",
    "version": "0.1.0",
    "changelog": {
        "0.1.0": "complete the model package",
        "0.0.1": "initialize the model package structure"
    },
    "monai_version": "0.9.0",
    "pytorch_version": "1.10.0",
    "numpy_version": "1.21.2",
    "optional_packages_version": {
        "nibabel": "3.2.1",
        "pytorch-ignite": "0.4.8",
        "einops": "0.4.1",
        "fire": "0.4.0",
        "timm": "0.6.7"
    },
    "task": "Renal segmentation",
    "description": "A transformer-based model for renal segmentation from T1W MRI image",
    "authors": "Vanderbilt University + MONAI team",
    "copyright": "Copyright (c) MONAI Consortium",
    "data_source": "RawData.zip",
    "data_type": "nibabel",
    "image_classes": "single channel data, intensity scaled to [0, 1]",
    "label_classes": "133 Classes",
    "pred_classes": "133 Classes",
    "eval_metrics": {
        "mean_dice": 0.71
    },
    "intended_use": "This is an example, not to be used for diagnostic purposes",
    "references": [
        "Xin, et al. Characterizing Renal Structures with 3D Block Aggregate Transformers. arXiv preprint arXiv:2203.02430 (2022). https://arxiv.org/pdf/2203.02430.pdf"
    ],
    "network_data_format": {
        "inputs": {
            "image": {
                "type": "image",
                "format": "hounsfield",
                "modality": "CT",
                "num_channels": 1,
                "spatial_shape": [
                    96,
                    96,
                    96
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    1
                ],
                "is_patch_data": true,
                "channel_def": {
                    "0": "image"
                }
            }
        },
        "outputs": {
            "pred": {
                "type": "image",
                "format": "segmentation",
                "num_channels": 4,
                "spatial_shape": [
                    96,
                    96,
                    96
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    1
                ],
                "is_patch_data": true,
                "channel_def": {
                    "0": "background",
                    "1": "To fill"
                }
            }
        }
    }
}

=== Project-MONAI/model-zoo/models/swin_unetr_btcv_segmentation/configs/metadata.json
{
    "schema": "https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json",
    "version": "0.1.0",
    "changelog": {
        "0.1.0": "complete the model package",
        "0.0.1": "initialize the model package structure"
    },
    "monai_version": "0.9.0",
    "pytorch_version": "1.10.0",
    "numpy_version": "1.21.2",
    "optional_packages_version": {
        "nibabel": "3.2.1"
    },
    "task": "BTCV multi-organ segmentation",
    "description": "A pre-trained model for volumetric (3D) multi-organ segmentation from CT image",
    "authors": "MONAI team",
    "copyright": "Copyright (c) MONAI Consortium",
    "data_source": "dataset.tar from https://www.synapse.org/#!Synapse:syn3193805/wiki/217752/",
    "data_type": "nibabel",
    "image_classes": "single channel data, intensity scaled to [0, 1]",
    "label_classes": "multi-channel data,0:background,1:spleen, 2:Right Kidney, 3:Left Kideny, 4:Gallbladder, 5:Esophagus, 6:Liver, 7:Stomach, 8:Aorta, 9:IVC, 10:Portal and Splenic Veins, 11:Pancreas, 12:Right adrenal gland, 13:Left adrenal gland",
    "pred_classes": "14 channels OneHot data, 0:background,1:spleen, 2:Right Kidney, 3:Left Kideny, 4:Gallbladder, 5:Esophagus, 6:Liver, 7:Stomach, 8:Aorta, 9:IVC, 10:Portal and Splenic Veins, 11:Pancreas, 12:Right adrenal gland, 13:Left adrenal gland",
    "eval_metrics": {
        "mean_dice": 0.8312
    },
    "intended_use": "This is an example, not to be used for diagnostic purposes",
    "references": [
        "Hatamizadeh, Ali, et al. 'Swin UNETR: Swin Transformers for Semantic Segmentation of Brain Tumors in MRI Images. arXiv preprint arXiv:2201.01266 (2022). https://arxiv.org/abs/2201.01266.",
        "Tang, Yucheng, et al. 'Self-supervised pre-training of swin transformers for 3d medical image analysis. arXiv preprint arXiv:2111.14791 (2021). https://arxiv.org/abs/2111.14791."
    ],
    "network_data_format": {
        "inputs": {
            "image": {
                "type": "image",
                "format": "hounsfield",
                "modality": "CT",
                "num_channels": 1,
                "spatial_shape": [
                    96,
                    96,
                    96
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    1
                ],
                "is_patch_data": true,
                "channel_def": {
                    "0": "image"
                }
            }
        },
        "outputs": {
            "pred": {
                "type": "image",
                "format": "segmentation",
                "num_channels": 14,
                "spatial_shape": [
                    96,
                    96,
                    96
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    1
                ],
                "is_patch_data": true,
                "channel_def": {
                    "0": "background",
                    "1": "spleen",
                    "2": "Right Kidney",
                    "3": "Left Kideny",
                    "4": "Gallbladder",
                    "5": "Esophagus",
                    "6": "Liver",
                    "7": "Stomach",
                    "8": "Aorta",
                    "9": "IVC",
                    "10": "Portal and Splenic Veins",
                    "11": "Pancreas",
                    "12": "Right adrenal gland",
                    "13": "Left adrenal gland"
                }
            }
        }
    }
}

=== Project-MONAI/model-zoo/models/endoscopic_inbody_classification/configs/metadata.json
{
    "schema": "https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json",
    "version": "0.3.0",
    "changelog": {
        "0.3.0": "update dataset processing",
        "0.2.2": "update to use monai 1.0.1",
        "0.2.1": "enhance readme on commands example",
        "0.2.0": "update license files",
        "0.1.0": "complete the first version model package",
        "0.0.1": "initialize the model package structure"
    },
    "monai_version": "1.0.1",
    "pytorch_version": "1.13.0",
    "numpy_version": "1.22.4",
    "optional_packages_version": {
        "nibabel": "4.0.1",
        "pytorch-ignite": "0.4.9"
    },
    "task": "Endoscopic inbody classification classification",
    "description": "A pre-trained binary classification model for endoscopic inbody classification task",
    "authors": "NVIDIA DLMED team",
    "copyright": "Copyright (c) 2021-2022, NVIDIA CORPORATION",
    "data_source": "private dataset",
    "data_type": "RGB",
    "image_classes": "three channel data, intensity [0-255]",
    "label_classes": "0: inbody, 1: outbody",
    "pred_classes": "vector whose length equals to 2, [1,0] means in body, [0,1] means out body",
    "eval_metrics": {
        "accuracy": 0.98
    },
    "references": [
        "J. Hu, L. Shen and G. Sun, Squeeze-and-Excitation Networks, 2018 IEEE/CVF Conference on Computer Vision and Pattern Recognition, 2018, pp. 7132-7141. https://arxiv.org/pdf/1709.01507.pdf"
    ],
    "network_data_format": {
        "inputs": {
            "image": {
                "type": "magnitude",
                "format": "RGB",
                "modality": "regular",
                "num_channels": 3,
                "spatial_shape": [
                    256,
                    256
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    1
                ],
                "is_patch_data": false,
                "channel_def": {
                    "0": "R",
                    "1": "G",
                    "2": "B"
                }
            }
        },
        "outputs": {
            "pred": {
                "type": "probabilities",
                "format": "classes",
                "num_channels": 2,
                "spatial_shape": [
                    1,
                    2
                ],
                "dtype": "float32",
                "value_range": [
                    0,
                    1
                ],
                "is_patch_data": false,
                "channel_def": {
                    "0": "in body",
                    "1": "out body"
                }
            }
        }
    }
}
